### ISSUE TITLE
Not able to understand the question

### ISSUE THREAD

**Issue by 23bca312** [vtcbca/internal-exam-23bca312#2]
[7. Create table contact(fname,laname,contact,email,city). Perform following operation on it.
   1. Insert Contact 8 records
   2. Delete Contact
   
   Create trigger to validate input on the contact table.

 Also maintain log regarding above operation in logtable with
 operation name with datetime. if inserted and deleted then maintain
 detail about fname,lname, contact and datatime.
   if record is delete then maintain logtable with old and new value of contacts.]

IN this question how many trigger should be created

**Comment by 23bca312** [comment]
How to create trigger validate input

**Comment by 23BCA284** [comment]
you need to create at least two triggers.

**Comment by 23bca312** [comment]
Which two triggers

**Comment by 23BCA284** [comment]
> Which two triggers

1. Input validate trigger
2. Log table trigger

**Comment by 23bca312** [comment]
I have created two triggers
1.insert_log 
2.delete_log
Please check my code once 
Is it right or any kind of change needed

**Comment by 23bca312** [comment]
cur.execute("select * from contacts_log")
rec=cur.fetchone()
print(rec)


This show none in output

**Comment by 23BCA284** [comment]
Ok , I will check your code

**Comment by 23BCA284** [comment]
I think here problem in your trigger creation please recheck your both trigger and mainly focus on insert_log trigger.

**Comment by 23bca300** [comment]
> I have created two triggers 1.insert_log 2.delete_log Please check my code once Is it right or any kind of change needed

here you need to create a another log table :
cur.execute('CREATE TABLE IF NOT EXISTS contac_logs (fname,laname,contact,email,city, time_added TIMESTAMP)')
it store your data...If you modify the contact table your contact_logs table will modify automatically.

**Comment by 23bca312** [comment]
I have created two tables
1.contact
2.contact_log
And created two triggers
1.insert_log
2.delete_log
BUT when I insert record or delete record contact_log shows NONE

**Comment by 23bca300** [comment]
> I have created two tables 1.contact 2.contact_log And created two triggers 1.insert_log 2.delete_log BUT when I insert record or delete record contact_log shows NONE

but why you created delete log ??

**Comment by 23bca312** [comment]
To keep the record of Which data has been deleted from contact

**Comment by 23bca300** [comment]
> To keep the record of Which data has been deleted from contact 
But you create a trigger .....Let me explain 
If you create a contact_log table then what ever query you perform the log table automatically modify ..So here you need to create before insert trigger only nothing else.

**Comment by 23BCA281** [comment]
Here are the steps to create trigger :-
1.Import sqlite3 in Jupyter Notebook.
2 .Connect to the database.
3. Create a cursor object using cursor().
4. Create a table.
5. Insert records.
6. Commit the transaction using commit().
7. Use cur.executemany() to insert multiple records.
8. Create a trigger for delete operations.
9. Select your data.
10. Use fetchall() to retrieve the data.
I HOPE THIS WILL HELP YOU!

@23bca312
